### ISSUE TITLE
GenerateReport API issues

### ISSUE THREAD

**Issue by Vainock** [crowdin/crowdin-api-client-js#102]
1. The enum entry of ReportsModel.Format is missing `JSON`, which should exist according to the [API Reference](https://support.crowdin.com/api/v2/#operation/api.projects.reports.post).
2. The field `languageId` of `TopMembersSchema` seems to be required, despite it not actually being required. You can send a request (e. g. via Postman) without this field and generate a report with all languages.
3. How do I set `dateFrom` and `dateTo` for `TopMembersSchema`? Am I missing something or is it a bug? If I try to set those fields besides my `unit`, `format` and `languageId`, VSC tells me it is not assignable. If I look into src/reports/index.js, they also seem to be missing.

Please correct me if these things are not actually issues, but intended behavior.

**Comment by Natalia936** [comment]
Hi! Thank you for your question, our devs will have a look and once we have updates, we'll inform you right away. As well, thank you in advance for your kind understanding

**Comment by yevheniyJ** [comment]
@Vainock fixed in v1.11.0
