### ISSUE TITLE
Question: How can I download all project files as zip?

### ISSUE THREAD

**Issue by PuneetGopinath** [crowdin/crowdin-api-client-js#111]
Is there a way to download all project files as zip?
If yes, please share
If no, please add that feature

**Comment by BozhenaDobrovolska** [comment]
Hi! You can build and download a peject in csv or xlsx:
![Screenshot (68)](https://user-images.githubusercontent.com/61051490/123530024-b0bac700-d6fe-11eb-9b3c-bd3b6643307f.png)

**Comment by PuneetGopinath** [comment]
> Hi! You can build and download a peject in csv or xlsx:
> ![Screenshot (68)](https://user-images.githubusercontent.com/61051490/123530024-b0bac700-d6fe-11eb-9b3c-bd3b6643307f.png)

Using the API?

**Comment by PuneetGopinath** [comment]
I need from the API. I think it was there in v1.

**Comment by BozhenaDobrovolska** [comment]
I'm afraid it is not possible via API(

**Comment by PuneetGopinath** [comment]
> I'm afraid it is not possible via API(

Can I request one?

**Comment by BozhenaDobrovolska** [comment]
I will create an improvement idea

Will keep you posted

**Comment by PuneetGopinath** [comment]
> I will create an improvement idea
> 
> Will keep you posted

Today I got a cool idea.
I first created a branch named "translations" on my repo, then I added a crowdin.yml and a new folder locales where I did put all my en-US translation files and set crowdin to sync to this branch.

And that's it, I just download all my files using GitHub URL (https://github.com/Welcome-Bot/welcome-bot/archive/refs/heads/translations.zip)

Still I think the feature request should be there. If that feature was there no need to all these problems.

**Comment by Rommka4** [comment]
Hello!

Cool idea!🙂

Sure, my colleague has already made an improvement idea at your request

We will keep you posted

**Comment by cbengtson** [comment]
Is there still no way to download all files via API v2?

**Comment by tattiza** [comment]
Hi!
There is a way to build your project translations with the following method: https://support.crowdin.com/api/v2/#operation/api.projects.translations.builds.post
And download project translations after that:
https://support.crowdin.com/api/v2/#operation/api.projects.translations.builds.download.download
