### ISSUE TITLE
Use different Axios instance

### ISSUE THREAD

**Issue by Vainock** [crowdin/crowdin-api-client-js#130]
Hello, I have trouble changing the http client to a different Axios instance.

```ts
import Axios from 'axios';
const axios = Axios.create(); // my instance works correctly and I'm able to send requests without any trouble
const { projectsGroupsApi } = new Crowdin({ token: 'myToken' }, { httpClient: axios}); // I already tried setting httpClientType to HttpClientType.AXIOS but this doesn't do anything
```

This does not work and the client is rather calling its own internal instance.
If you could provide a sample of how to achieve this I would be very grateful!

**Comment by Olena1234** [comment]
Hello! Let us please check this and come back on the matter

**Comment by yevheniyJ** [comment]
@Vainock You are specifing wrong url to the API. And the url to the API itself is dynamically constructed based on if you are using v2 or enterprise version of the API. But there is a field `url` which is publicly available that you can use (e.g. in tests).

Here is working example
```javascript
const { projectsGroupsApi } = new Crowdin({ token: 'myTestToken' }, { httpClient: axios });

beforeAll(() => {
	const body = { targetLanguageIds: ['de', 'fr'], targetLanguages: [{ locale: 'de-DE', id: 'de' }] };
	nock(projectsGroupsApi.url)
		.persist()
		.get(`/projects/${projectId}`)
		.reply(200, function () {
			return JSON.stringify(body);
		});
});

it('Axios', async () => {
	console.log((await axios.get(`${projectsGroupsApi.url}/projects/${projectId}`)).data);
});

it('Crowdin Client', async () => {
	console.log((await projectsGroupsApi.getProject(projectId)).data);
});
```
As you can see now url is not hardcoded but extracted from crowdin library. Both tests are green now.
