### ISSUE TITLE
GNU

### ISSUE THREAD

**Issue by Enrique-porras** [crowdin/crowdin-api-client-js#134]
chrome-distiller://2c0be80d-e5cb-4f9d-9ad1-3d72227a2180_de6ad93247a230656cc1e5ce68158e0250b571b6778eb2873fc8eaf73c40fc0f/?title=Preguntas+frecuentes+acerca+de+las+licencias+de+GNU+-+Proyecto+GNU+-+Free+Software+Foundation&url=https%3A%2F%2Fwww.gnu.org%2Flicenses%2Fgpl-faq.html

**Comment by Vainock** [comment]
@andrii-bodnar You can block users from spamming: https://github.blog/2016-04-04-organizations-can-now-block-abusive-users/

**Comment by andrii-bodnar** [comment]
@Vainock thanks for the suggestion, already blocked :slightly_smiling_face:
