### ISSUE TITLE
RFC: Reject and throw only error instances

### ISSUE THREAD

**Issue by cdaringe** [crowdin/crowdin-api-client-js#160]
# Problem

Crowdin throws/rejects non-errors, which is generally considered an anti-pattern.

```js
if (error.response.status === 400) {
  return Promise.reject(error.response.data);
}                
```

# Discussion

`Error` instances have predictable control flow semantics. Though it can never be safely assumed,

```js
try {
  foo()
} catch (err) {
  err // where`err instanceof Error` yields `true`
}
```

is generally considered a best practice. In this regard, error handlers can pick off `message` & `stack` accordingly.

# Recommendation

Throw the original Error, _or_, create a new `Error` instance that extends `Error` to decorate your values on.

**Comment by yevheniyJ** [comment]
Improvement available in v1.18.0
