### ISSUE TITLE
buildProjectDirectoryTranslation method fails with error "Unsupported Content-Type Header"

### ISSUE THREAD

**Issue by j1stDS** [crowdin/crowdin-api-client-js#169]
While some methods work properly (e.g. buildProject) this one fails with exception:
```
{
  "message": "Unsupported Content-Type Header",
  "code": 415
}
```

Performing my request like this
`
let {data: {id}} = await translationsApi.buildProjectDirectoryTranslation(PROJECT_ID, DIRECTORY_ID);
`

Also then I tried to make request with axios, it was successful as well:
```
let data = await axios.post(`https://libertexgroup.crowdin.com/api/v2/projects/${PROJECT_ID}/translations/builds/directories/${DIRECTORY_ID}`, {}, {
    headers: {
        Authorization: `Bearer ${API_KEY}`
    }
});
```
Environment:
nodejs v16.13.1
crowdin-api-client-js v1.17.0

**Comment by yevheniyJ** [comment]
fixed in v1.17.1
