### ISSUE TITLE
How can I add comment to a task 

### ISSUE THREAD

**Issue by vaxt** [crowdin/crowdin-api-client-js#186]
Is there a api ? I didn't find one in d document

**Comment by dianaIosm** [comment]
Hello @vaxt! When creating a task you can add a description (comment) to the task, using the following API method: https://developer.crowdin.com/api/v2/#operation/api.projects.tasks.post

**Comment by vaxt** [comment]
> Hello @vaxt! When creating a task you can add a description (comment) to the task, using the following API method: https://developer.crowdin.com/api/v2/#operation/api.projects.tasks.post

Thanks for your reply. Yes ,I can add or edit description  using API.
But I think comment is different from description .

This is a description  on web:
![image](https://user-images.githubusercontent.com/14368387/184076264-9fe6dbbf-8ed3-4d23-88fe-215e6fb1a4ca.png)
This is a comment  on web:
![image](https://user-images.githubusercontent.com/14368387/184076179-f36a1507-8b3d-49c6-bbdd-4b484d213c7e.png)
BTW,  the get Task method I found here : [https://developer.crowdin.com/api/v2/#operation/api.projects.tasks.get](https://developer.crowdin.com/api/v2/#operation/api.projects.tasks.get)  return the comment count ,  but no comment details

**Comment by dianaIosm** [comment]
Currently, there's no option to add comments to tasks through API. I have already passed the improvement idea, but unfortunately, I can't give you an ETA of the implementation.
