### ISSUE TITLE
autoTag on existing screenshots is not supported

### ISSUE THREAD

**Issue by djbb7** [crowdin/crowdin-api-client-js#204]
Using the API (https://developer.crowdin.com/api/v2/#operation/api.projects.screenshots.tags.putMany) it is possible to autoTag an existing image by providing the body:

```json
{
  "autoTag": true
}
```

However, the js client only supports passing the list of tags that should be added (https://github.com/crowdin/crowdin-api-client-js/blob/master/src/screenshots/index.ts#L147)
```typescript
    replaceTags(projectId: number, screenshotId: number, request: ScreenshotsModel.AddTagRequest[]): Promise<void> {
        const url = `${this.url}/projects/${projectId}/screenshots/${screenshotId}/tags`;
        return this.put(url, request, this.defaultConfig());
    }
```

The signature of the `replaceTags` method should be updated so that `autoTag` is also supported.

**Comment by yevheniyJ** [comment]
Fixed in v1.21.1
