### ISSUE TITLE
RFC: Refactor handleError to explicitly accept Error instances

### ISSUE THREAD

**Issue by cdaringe** [crowdin/crowdin-api-client-js#225]
# Problem

Our SDK uses crowdin, however, crowdin emits unhelpful errors.

Specifically, generic errors are produced here: https://github.com/crowdin/crowdin-api-client-js/blob/efe986e2446c2c4a7050888a14675732dab6341f/src/core/index.ts#L157

# Discussion

- `handleError` should be refactored to expect only error instance.
- all callsites that are not passing explict Error instances will begin to fail `tsc`
- every callsites in violation of not passing an Error instance should coerce their failure into an Error instance, adding the context that is currently missing in handleError.

because handleError accept `any`, generic errors happen and the user experience is poor. developers do not have any inclination as to the failure mode. this is easily solved by forcing all handleError callsites to provide Error instances with adequate context in their message fields

**Comment by DimaYashchyshyn** [comment]
Thanks for the report, checking

**Comment by andrii-bodnar** [comment]
@cdaringe thanks a lot for your request. Could you please provide some examples of how you use this API Client? This can help us in further investigation.

@yevheniyJ do you have some ideas on the matter? 🙂

**Comment by cdaringe** [comment]
Sure! Its closed source, but we pretty much use only listStrings, addString, and listTranslations from the crowdin api client.

if you look at where handleError is used, it looks to be mainly attached to http client error handlers. handleError expects an Error nested on an .error field, but you can see various places where this re nesting is not occurring. Removing the use of any, and replacing the params with just (error: Error) or (e: { error: Error }) will probably force health refactors at call sites

**Comment by cdaringe** [comment]
i'm going to try and take a stab at this now
