### ISSUE TITLE
crowdin is not a constructor.

### ISSUE THREAD

**Issue by MSAbaddon** [crowdin/crowdin-api-client-js#284]
Hi,
I just tried using your coding since I'm looking for a way to update string labels.

However, when I use your example code I get the error message "crowdin is not a constructor".

Are the examples still up to date or am I doing anything wrong? I'm no coding expert tbh.

import crowdin from '@crowdin/crowdin-api-client';

const { translationsApi } = new crowdin({
    token: 'token',
    organization: 'org'
});

**Comment by dies** [comment]
this is interesting. the following code worked for me. let us update you tomorrow on why your code is not working, it seems perfectly valid

```javascript
import crowdin from '@crowdin/crowdin-api-client';

const api = new crowdin.default({
    token: 'xxx',
    organization: 'xxx'
});

console.log((await api.languagesApi.listSupportedLanguages()).data);
```

I'm using `new crowdin.default` instead of `new crowdin`

**Comment by MSAbaddon** [comment]
Yeah, I just Ran some testing a few minutes ago. new crowdin.default works fine for ES6, new crowdin does not.

**Comment by MSAbaddon** [comment]
After some more tests I can verify that new crowdin.default works fine. Maybe you should just update your examples for ES6.

**Comment by dies** [comment]
Thank you for your confirmation! We will make sure to update the examples
