### ISSUE TITLE
Reports API changes

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-js#292]
Crowdin recently released a big update of the reports functionality. Now, when calculating the price for translation in Cost Estimation and Translation Cost reports, we have introduced a new feature that allows you to include the cost of proofreading if the source text matches the Translation Memory (TM) or Machine Translation (MT) results.

The reports API was updated as well. The legacy *Cost Estimate* (including Fuzzy mode)  and *Translation Cost* reports were deprecated in favor of the new *Cost-Estimation Post-Editing* and *Translation Costs Post-Editing* reports. The legacy reports will be removed in future releases.

**API reference:**

- [Generate Report](https://developer.crowdin.com/api/v2/#operation/api.projects.reports.post) (crowdin.com)
- [Generate Group Report](https://developer.crowdin.com/enterprise/api/v2/#operation/api.groups.reports.post) (Crowdin Enterprise)
- [Generate Organization Report](https://developer.crowdin.com/enterprise/api/v2/#operation/api.reports.post) (Crowdin Enterprise)
- [Generate Report](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.reports.post) (Crowdin Enterprise)

The **Report Settings Template** API was also affected (refer to the API Docs for details).

Deprecated forms should be marked as deprecated in this API Client, and the new forms should be added.

**Comment by yevheniyJ** [comment]
Implemented in #308 and available in v1.25.0
