### ISSUE TITLE
Add the JavaScript File Export Options

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-js#295]
Crowdin recently added the ability to configure the export options for JavaScript files. This is a great feature, but it's not yet supported by the API Client.

- `exportPattern` - string, File export pattern. Defines file name and path in resulting translations bundle.
- `exportQuotes` - string enum `single` or `double`. Defines quotes to be used in resulting translations bundle.

The new options need to be added to this API Client.

**API Reference:**

- [Add File](https://developer.crowdin.com/api/v2/#operation/api.projects.files.post)
- [Edit File](https://developer.crowdin.com/api/v2/#operation/api.projects.files.patch)
- [Get File](https://developer.crowdin.com/api/v2/#operation/api.projects.files.get)

**Comment by balogun14** [comment]
@andrii-bodnar can you explain this issue more I will like to work on this

**Comment by andrii-bodnar** [comment]
@balogun14 the new request options should be added.

Related code:

- https://github.com/crowdin/crowdin-api-client-js/blob/master/src/sourceFiles/index.ts#L551

Please also check the other places including Unit tests.

Similar PRs in other API clients:

- https://github.com/crowdin/crowdin-api-client-java/pull/178/
- https://github.com/crowdin/crowdin-api-client-python/pull/117/

**Comment by balogun14** [comment]
@andrii-bodnar https://github.com/crowdin/crowdin-api-client-js/blob/master/src/sourceFiles/index.ts#L551
So I am meant to modify this file

**Comment by andrii-bodnar** [comment]
@balogun14 yes, but please also check the other places including Unit tests. There might be more files required to be changed for this feature

**Comment by balogun14** [comment]
@andrii-bodnar okay i will start working on this now
