### ISSUE TITLE
Strings Exporter Settings API

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-js#300]
Crowdin recently added a bunch of new API methods to manage Strings Exporter settings for some file formats.

The new methods need to be added to this API Client.

**API Reference:**

- [List Project Strings Exporter Settings](https://developer.crowdin.com/api/v2/#operation/api.projects.strings-exporter-settings.getMany)
- [Add Project Strings Exporter Settings](https://developer.crowdin.com/api/v2/#operation/api.projects.strings-exporter-settings.post)
- [Get Project Strings Exporter Settings](https://developer.crowdin.com/api/v2/#operation/api.projects.strings-exporter-settings.get)
- [Delete Project Strings Exporter Settings](https://developer.crowdin.com/api/v2/#operation/api.projects.strings-exporter-settings.delete)
- [Edit Project Strings Exporter Settings](https://developer.crowdin.com/api/v2/#operation/api.projects.strings-exporter-settings.patch)

**Comment by nelvson** [comment]
hi, is this issue still open?

**Comment by andrii-bodnar** [comment]
Hi @nelvson, yes, assigning it to you

**Comment by kisharnath** [comment]
@andrii-bodnar can I work on this issue also?

**Comment by andrii-bodnar** [comment]
@kisharnath definitely, assigning it to you, thank you!
