### ISSUE TITLE
Apply Pre-Translation API: add labels support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-js#302]
Crowdin has recently added a possibility to Pre-Translate strings by labels. However, the new parameters are not supported in this API client.

The new `labelIds` and `excludeLabelIds` parameters should be added to the "Apply Pre-Translation" method in this API client.

**API Reference:**

- [Apply Pre-Translation](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.pre-translations.post)
- [Pre-Translation Status](https://developer.crowdin.com/enterprise/api/v2/#tag/Translations/paths/~1projects~1{projectId}~1pre-translations~1{preTranslationId}/get) (The `attributes` field now contains the new fields as well)

**Comment by KyleGrande** [comment]
Hey! So does this just require an update to the PreTranslateRequest interface or am I misunderstanding?

**Comment by andrii-bodnar** [comment]
Hi @KyleGrande, yes, it's related to the `PreTranslateRequest`, `PreTranslationStatusAttributes`, and probably something else related to the Pre-Translation including Unit tests (needs to be checked in the code).

**Comment by KyleGrande** [comment]
Thanks @andrii-bodnar for further clarifying. I will look more into it and begin working.

**Comment by andrii-bodnar** [comment]
@KyleGrande I think it would be nice to add a new test case in the [tests/translations/api.test.ts](https://github.com/crowdin/crowdin-api-client-js/blob/master/tests/translations/api.test.ts)

**Comment by andrii-bodnar** [comment]
@KyleGrande looks good to me, thanks a lot for the contribution! 🚀
