### ISSUE TITLE
Applications API support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-js#309]
Crowdin has recently added new endpoints for managing custom applications. Support for these endpoints is missing in this Crowdin API client.

We need to add support for the following endpoints:

- [Get Application Data](https://developer.crowdin.com/api/v2/#operation/api.applications.api.get)
- [Update or Restore Application Data](https://developer.crowdin.com/api/v2/#operation/api.applications.api.put)
- [Add Application Data](https://developer.crowdin.com/api/v2/#operation/api.applications.api.post)
- [Delete Application Data](https://developer.crowdin.com/api/v2/#operation/api.applications.api.delete)
- [Edit Application Data](https://developer.crowdin.com/api/v2/#operation/api.applications.api.patch)

**Comment by AksBad007** [comment]
Hi, if this is still is open, I'd like to be assigned.
