### ISSUE TITLE
Report Settings Template: add the `isPublic` property support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-js#310]
The Report Settings Template API now supports the ability to create public templates. We need to add support for the `isPublic` property to this Crowdin API client.

**References:**

- [Add Report Settings Template](https://developer.crowdin.com/api/v2/#operation/api.projects.reports.settings-templates.post)
- [Get Report Settings Template](https://developer.crowdin.com/api/v2/#operation/api.projects.reports.settings-templates.get) (response)

**Comment by abuna1985** [comment]
@andrii-bodnar Can I please be assigned this issue?

**Comment by andrii-bodnar** [comment]
@abuna1985 sure, thank you!

**Comment by abuna1985** [comment]
Absolutely. Apologies for the delay. I will have a pull request for this in later today. This is my first opportunity to update an API. Very excited to see how it works.

**Comment by andrii-bodnar** [comment]
@abuna1985 Exactly! Thanks, I look forward to reviewing the PR!
