### ISSUE TITLE
Source Files: add the `context` property support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-js#312]
The Source Files API now supports the possibility to specify the `context` for the whole file. We need to add support for the `context` property to this Crowdin API client.

**References:**

- [Add File](https://developer.crowdin.com/api/v2/#operation/api.projects.files.post)
- [Edit File](https://developer.crowdin.com/api/v2/#operation/api.projects.files.patch)
- [Get file](https://developer.crowdin.com/api/v2/#operation/api.projects.files.get) (response)

**Comment by yevheniyJ** [comment]
Added in v1.25.1
