### ISSUE TITLE
Strings translations APIs: add new parameters support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-js#316]
Several String Translation API endpoints have been enhanced with new parameters support: `labelIds`, `excludeLabelIds`. These parameters should be added to this API client.

**References:**

- [List Translation Approvals](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.approvals.getMany)
- [List Translation Votes](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.votes.getMany)

**Comment by faizan1191** [comment]
@andrii-bodnar please assign this issue to me and please review the changes in the linked PR.

Thanks!!
