### ISSUE TITLE
Applications API: add support for new endpoints

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-js#346]
Crowdin has recently released new endpoints for the Applications API. We need to add support for them in the Crowdin API client as well.

**API reference:**

- [List Application Installations](https://developer.crowdin.com/api/v2/#operation/api.applications.installations.getMany)
- [Install Application](https://developer.crowdin.com/api/v2/#operation/api.applications.installations.post)
- [Get Application Installation](https://developer.crowdin.com/api/v2/#operation/api.applications.installations.get)
- [Delete Application Installation](https://developer.crowdin.com/api/v2/#operation/api.applications.installations.delete)
- [Edit Application Installation](https://developer.crowdin.com/api/v2/#operation/api.applications.installations.patch)

**Comment by AksBad007** [comment]
Hi, if this is still open, I'd like to be assign.

**Comment by andrii-bodnar** [comment]
@AksBad007 it's open, assigning it to you, thanks!

**Comment by crowdin-support** [comment]
Hello,

Thank you for reaching Crowdin team!

Our responses may be slower than usual, but we will do our best to get back
to you as soon as possible. Live chat and fast email support will be
restored on January 2nd at 5am UTC.

Any urgent inquiries will be resolved with the higher priority in the
queue, inbox is still monitored once in a while 👍

All the best in 2024! 🐲

--
Sincerely yours,
Crowdin Team
{#HS:2467753535-266180#}
