### ISSUE TITLE
Webhook event - source string change trigger

### ISSUE THREAD

**Issue by eligutovsky** [crowdin/crowdin-api-client-js#349]
Hello,

While searching for the 'string.updated' event trigger for webhook, I noticed an inconsistency between the Crowdin [JS lib](https://github.com/crowdin/crowdin-api-client-js/blob/ccc976dd26ad058e29e682bc90b38dadda425295/src/webhooks/index.ts#L115) and [.NET lib](https://github.com/crowdin/crowdin-api-client-dotnet/blob/dfa508277f176646200dc9a7852cdab164fcb03f/src/Crowdin.Api/Webhooks/EventType.cs), as these events are described in the [docs](https://developer.crowdin.com/api/v2/#operation/api.projects.webhooks.post). Is this a lack of implementation or was it done on purpose?

**Comment by andrii-bodnar** [comment]
Hi @eligutovsky,

It's not on purpose and needs to be updated in the JS API client.

**Comment by Zahid92** [comment]
Hi @andrii-bodnar, may I take this one ?

**Comment by andrii-bodnar** [comment]
Hi @Zahid92, sure, thank you!
