### ISSUE TITLE
Security Logs API support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-js#364]
Crowdin has recently released a new API methods to get information about security logs. It would be great to add support of these methods to the Crowdin API client.

**References:**

- [List User Security Logs](https://developer.crowdin.com/api/v2/#operation/api.users.security-logs.getMany)
- [Get User Security Log](https://developer.crowdin.com/api/v2/#operation/api.users.security-logs.get)
- [List Organization Security Logs](https://developer.crowdin.com/enterprise/api/v2/#operation/api.security-logs.getMany) (Crowdin Enterprise)
- [Get Organization Security Log](https://developer.crowdin.com/enterprise/api/v2/#operation/api.security-logs.get) (Crowdin Enterprise)

**Comment by kisharnath** [comment]
Hey please assign this to me

**Comment by andrii-bodnar** [comment]
Hi @kisharnath!

We'll be adding the `createdAfter` (string), `createdBefore` (string) query parameters to the **List User Security Logs** and **List Organization Security Logs** methods soon.

Please take them into account during implementation. Thank you!

**Comment by andrii-bodnar** [comment]
Hi @kisharnath, do you have any updates on this?

**Comment by kisharnath** [comment]
I am working on this .Will send a pr this week
