### ISSUE TITLE
Some Branch methods are missing in the client

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-js#380]
Crowdin's string-based projects include some additional API methods for working with branches:

- [Get Cloned Branch](https://developer.crowdin.com/api/v2/string-based/#operation/api.projects.branches.clones.branch.get)
- [Clone Branch](https://developer.crowdin.com/api/v2/string-based/#operation/api.projects.branches.clones.post)
- [Check Branch Clone Status](https://developer.crowdin.com/api/v2/string-based/#operation/api.projects.branches.clones.get)
- [Merge Branch](https://developer.crowdin.com/api/v2/string-based/#operation/api.projects.branches.merges.post)
- [Check Branch Merge Status](https://developer.crowdin.com/api/v2/string-based/#operation/api.projects.branches.merges.get)
- [Get Branch Merge Summary](https://developer.crowdin.com/api/v2/string-based/#operation/api.projects.branches.merges.summary.get)

These methods should also be included in this API client, along with the existing branch methods, and covered by unit tests.

https://github.com/crowdin/crowdin-api-client-js/blob/master/src/sourceFiles/index.ts

**Comment by jimmysafe** [comment]
totally agree, i see many other methods missing from the js client.
Also i would like to point out that the Crowdin webapp uses an endpoint which is not available in the api for some strange reason:

`https://api.crowdin.com/api/v2/projects/PROJECTID/branches/BRANCHID/merges/MERGEID/conflicts`

This endpoint is providing all conflicted strings when we try to merge. 
In our case this is crucial and it would make a huge difference if we could get this endpoint.

please make it available! along with all those other missing! please <3

**Comment by andrii-bodnar** [comment]
Hi @jimmysafe, thanks for pointing this out!

I have already passed it on to the team regarding the conflicts endpoint.

Could you please provide more info on the missing APIs in the client? It would be great to have issues for these endpoints as well.

**Comment by rodrigolourenco** [comment]
Hey @yevheniyJ, by any chance could you also include the merge methods?

[Merge Branch](https://developer.crowdin.com/api/v2/string-based/#operation/api.projects.branches.merges.post)
[Check Branch Merge Status](https://developer.crowdin.com/api/v2/string-based/#operation/api.projects.branches.merges.get)
[Get Branch Merge Summary](https://developer.crowdin.com/api/v2/string-based/#operation/api.projects.branches.merges.summary.get)

**Comment by yevheniyJ** [comment]
@rodrigolourenco it's now available in latest version
