### ISSUE TITLE
ListQaCheckIssuesOptions interface limits the use of API capabilities

### ISSUE THREAD

**Issue by Passiday** [crowdin/crowdin-api-client-js#382]
ListQaCheckIssuesOptions interface that is used in the listQaCheckIssues method of TranslationStatus class does not let to use the API to it's full potential: the API allows passing several comma-separated values in "category" and "validation" parameters, but this JavaScript implementation lets user to select only one value.

API endpoint docs: https://developer.crowdin.com/api/v2/#operation/api.projects.qa-checks.getMany

I don't dare to submit a patch, but a possible solution would be to allow passing an array of Category (or Validation) type values:
```
    interface ListQaCheckIssuesOptions extends PaginationOptions {
        category?: Category | [Category];
        validation?: Validation | [Validation];
        languageIds?: string;
    }
```
.. and then updating the listQaCheckIssues method accordingly, to handle the array values.

**Comment by andrii-bodnar** [comment]
Hi @Passiday, thanks for pointing this out!

I think the suggested solution would be great, it also doesn't break backward compatibility, which is important in this case. We can add a `TODO` there to remember about it and leave an array type in the future major release.

@yevheniyJ what do you think?
