### ISSUE TITLE
Merge job not found - 404

### ISSUE THREAD

**Issue by jimmysafe** [crowdin/crowdin-api-client-js#412]
Hi,

I am trying to use the Crowdin API V2 (Strings) to merge a branch and get the merge branch status.

Here is my code:

```
    let res = await api.post<any, AxiosResponse<MergeBranchResponse>>(
      `/branches/${mainBranch?.data.id}/merges`,
      {
        dryRun: false,
        sourceBranchId: branchId,
        deleteAfterMerge: true,
      }
    );

    do {
      res = await checkMergeBranchStatus(branchId, res.data.data.identifier);
      if (res.data.data.status !== "finished") {
        await new Promise((r) => setTimeout(r, 1000));
      }
    } while (res.data.data.status !== "finished");
    
    return res.data
```

the first query runs fine and i get a merge identifier along with the merge response [described in the docs ](https://developer.crowdin.com/api/v2/string-based/#operation/api.projects.branches.merges.post) .

the second query `checkMergeBranchStatus` which simply calls the [get merge branch status endpoint](https://developer.crowdin.com/api/v2/string-based/#operation/api.projects.branches.merges.get) keep throwing a 404.

here the response:

<img width="884" alt="Screenshot 2024-07-16 at 14 16 19" src="https://github.com/user-attachments/assets/09b957ba-057b-41b6-8c86-bf51d69f4293">

few weeks ago this was working, now not anymore.

Please let me know if you need additional information.

Thanks in advance.

**Comment by andrii-bodnar** [comment]
Hi @jimmysafe, this seems to be an API-related issue. Could you please [contact](https://crowdin.com/contacts) our customer success service on this matter?
