### ISSUE TITLE
Reports APIs: Add support for the new Pre-Translate Efficiency Report

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-js#420]
The new Pre-Translate Efficiency Report is now available in the Crowdin Reports API. It is used to assess the effectiveness of pre-translation methods.

**Things to do:**

- Add support for the new report to this API client.
- Remove the obsolete report types (see the API documentation for the list of relevant types).

**References:**

- [Generate Report](https://support.crowdin.com/developer/api/v2/#tag/Reports/operation/api.projects.reports.post)

**Comment by prabhavnegi** [comment]
Hi @andrii-bodnar 
Created a new pull request for this issue
