### ISSUE TITLE
Projects API: `defaultTmId`, `defaultGlossaryId` support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-js#421]
The "Add Project", "Edit Project" API endpoint now supports the `defaultTmId` and `defaultGlossaryId` parameters. This allows you to set the default Translation Memory and Glossary for a project.

**Things to do:**

- Add new parameters to the Add Project and Edit Project methods.
- The Get Project response now also includes the default TM and Glossary IDs. It should be updated to reflect this change.

**References:**

- [Add Project](https://support.crowdin.com/developer/api/v2/#tag/Projects/operation/api.projects.post)
- [Edit Project](https://support.crowdin.com/developer/api/v2/#tag/Projects/operation/api.projects.patch)
- [Get Project](https://support.crowdin.com/developer/api/v2/#tag/Projects/operation/api.projects.get)

**Comment by prabhavnegi** [comment]
Hi @andrii-bodnar 
I made the following changes:
![Screenshot 2024-09-13 220017](https://github.com/user-attachments/assets/13542af2-833a-4790-b652-4d3429d0ba93)

Is that okay for this issue ?

**Comment by andrii-bodnar** [comment]
Hi @prabhavnegi, please create a PR and then we'll see. It's hard to review from screenshots.

**Comment by prabhavnegi** [comment]
@andrii-bodnar I have created the PR.
