### ISSUE TITLE
How to upload a new revision of the file?

### ISSUE THREAD

**Issue by erickskrauch** [crowdin/crowdin-api-client-js#60]
Hi. I'm trying to migrate my script for uploading/downloading strings and I faced the problem, that there is no way to attach a file to upload it to the Crowdin. Previously I have used [API client library for v1](https://github.com/peakon/crowdin-api#readme) and [it was worked fine](https://github.com/elyby/accounts-frontend/blob/e47eaf720f0c61df146d0b4559cace9aa464c98e/packages/scripts/i18n-crowdin.ts#L342). Now I need the same method for v2.

But the problem is that even [in the documentation](https://support.crowdin.com/api/v2/#operation/api.projects.files.put) there is no mention about how to attach the file to the request. This library also allows only to specify the import/export params and some `storageId`, which I have no idea why.

Can you help me, please?

**Comment by denisqua** [comment]
Hello @erickskrauch!

Will definitely pass your request to the developers and we'll get back to you with answer!

p.s. since it's a night at our end - developers are out of the work

**Comment by andrii-bodnar** [comment]
Hi @erickskrauch !

With Crowdin API v2 all files such as files for localization, screenshots, Glossaries, and Translation Memories should be first uploaded to the Storage. After you upload file to the Storage it will have a unique storage id using which you can then add the file to the project.

For example, to upload a localization file to your project, you need to run the following sequence of API methods:

[Add Storage](https://support.crowdin.com/api/v2/#operation/api.storages.post) – upload localization file body to storage at Crowdin server
[Add File](https://support.crowdin.com/api/v2/#operation/api.projects.files.post) – define where to add the localization file with specific storage id

For example:

```
import crowdin from '@crowdin/crowdin-api-client';

const { sourceFilesApi, uploadStorageApi } = new crowdin({
  token: 'personalAccessToken',
  organization: 'organizationName' // optional
});

async function addFile() {
  try {
    const storage = await uploadStorageApi.addStorage(<fileName>, <content>);
    const storageId = storage.data.id;

    await sourceFilesApi.createFile(<projectId>, {
            storageId: storageId,
            name: <fileName>
        });
  } catch (error) {
    console.error(error);
  }
}
```

**Comment by erickskrauch** [comment]
@andrii-bodnar, thanks, it helped me. [The current solution](https://github.com/elyby/accounts-frontend/blob/57cf6b377640f184dd7f5adfc1e2d4a58af40cc1/packages/scripts/i18n-crowdin.ts#L210-L236).
