### ISSUE TITLE
CreateTaskRequest has incorrectly required field: workflowStepId

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [crowdin/crowdin-api-client-js#74]
`CreateTaskRequest` has incorrectly required field: `workflowStepId`.

Spotted when using the client (version 1.8.12) to add tasks from TypeScript.

It's defined as:

```
    export interface CreateTaskRequest {
        workflowStepId: number;
        // ...
     }
```

See https://github.com/crowdin/crowdin-api-client-js/blob/c3b5a7c631ea515abf5dbdebd9138ceb14cdd8e3/src/tasks/index.ts#L123

I can successfully create tasks without this field. As far as I can tell, the OpenAPI definition (from https://support.crowdin.com/api/v2/) doesn't define this field for the add/create operation at all, only for Task itself.

**Comment by andrii-bodnar** [comment]
Hi @microbit-matt-hillsdon, Thanks for pointing out!

The `workflowStepId` field is required for Crowdin Enterprise [task creation](https://support.crowdin.com/enterprise/api/#operation/api.projects.tasks.post).

Definitely, it shouldn't be required in `CreateTaskRequest`. We will make it optional.

**Comment by yevheniyJ** [comment]
Fixed in v.1.8.13
