### ISSUE TITLE
v1 API Keys are broken

### ISSUE THREAD

**Issue by AlexanderZanin** [crowdin/crowdin-api-client-js#76]
After the latest release the API Keys for API v1 stooped to work.

Steps to reproduce: 

1. Go to the https://crowdin.com/settings#api-key
2. Copy or Generate new API key under the "Account API key" title
3. Take an appropriate Project identifier for API V1 in the "API & Webhooks" menu tab.
4. Make a request to https://api.crowdin.com/api/project/{project-identifier}/download/all.zip?key={project-key}

The response after using the updated API key:
`<?xml version="1.0" encoding="UTF-8"?>
<error>
    <code>1</code>
    <message>Requested project doesn't exist or the API key is invalid</message>
</error>`

While the old API keys that were generated before the update still work.

**Comment by BozhenaDobrovolska** [comment]
Hi Alexander,

Could you please try to change your request according to the second example?
![Screenshot - 2020-08-06T115733 871](https://user-images.githubusercontent.com/61051490/89514104-1435c080-d7de-11ea-9f26-f1c926da2fb9.png)

**Comment by AlexanderZanin** [comment]
Hi @BozhenaDobrovolska!

Thanks for the fast reaction. Second example works.
But there is one more issue.
On the current project we don't call the api directly as shown in the example but we use the crowdin library (https://www.npmjs.com/package/crowdin/v/1.0.0) and I don't see a possibility to pass the additional query param and change "key" to the "account-key".  All those endpoints with query params are already hardcoded inside the package.

Is it possible to use endpoint like it shown in the 1st example or should I consider forking the https://www.npmjs.com/package/crowdin/v/1.0.0 package to add a possibility customise the endpoint url?

**Comment by BozhenaDobrovolska** [comment]
@AlexanderZanin I'm afraid you need to fork the package since we removed API project key. I'm sorry to say that

**Comment by AlexanderZanin** [comment]
@BozhenaDobrovolska ok, got it. Thank you!
