### ISSUE TITLE
translationsApi.buildProject ignores parameters and just downloads latest build

### ISSUE THREAD

**Issue by hatton** [crowdin/crowdin-api-client-js#85]
I'm using crowdin-api-client version 1.9.0.

```
const buildRequestResult = await crowdinAccess.translationsApi.buildProject(
            kCrowdinProjectId,
            {
                exportApprovedOnly: false, 
                skipUntranslatedStrings: false,
            }
        );
console.log(JSON.stringify(buildRequestResult, null, 4));
```

If a build is already available, this returns that build, ignoring the arguments in my BuildRequest.  For example, right now the above is returning 

```
{
    "data": {
        "id": 24,
        "projectId": 261564,
        "status": "finished",
        "progress": 100,
        "attributes": {
            "branchId": null,
            "targetLanguageIds": [],
            "skipUntranslatedStrings": true, <--- not what I asked for
            "skipUntranslatedFiles": false,
            "exportApprovedOnly": true  <--- not what I asked for
        }
    }
}
```

If I do something on Crowdin.com to cause the build to become out of date, then the next time I run the above, it starts a new build and when it is done, I get the parameters I was asking for.  Is there a call I can make to force a new build when I change the parameters?

**Comment by Olena1234** [comment]
Hi there! Could you please share project name, so I will check everything from our side?

**Comment by hatton** [comment]
Sure. sil-bloom, Thanks.

**Comment by Olena1234** [comment]
Thank you!

**Comment by Olena1234** [comment]
Hi there! We have tested everything from our side, and unfortunately can not reproduce the issue. We run build with the specific parameters, received "inProgress" status, and in a while "finished" status. Then immediately run build with another parameters, received "inProgress" status and then "finished". So each new build included new parameters. Could you please specify requests with parameters that you run in your project? Maybe it would help us understand the situation better

**Comment by yevheniyJ** [comment]
In addition want to add that we tried above scenario in both ways (via js client and directly through REST requests). But as @Olena1234  described, we did not reproduce this issue.
