### ISSUE TITLE
Leading whitespace is getting trimmed when adding a translation to a string in a chrome JSON source file

### ISSUE THREAD

**Issue by chriswheeldon-peakon** [crowdin/crowdin-api-client-js#87]
Hello all, I've noticed what looks like a bug in either this library or the handling of API v2 requests by the crowdin platform.

If I have a project with a chrome JSON source file and programmatically add a translation that contains leading whitespace characters then the whitespace characters are trimmed from the submitted translation at some point. This can be seen both when the translation is viewed in the crowdin UI and when returned by the API.

I don't think this is correct and the crowdin UI itself agrees: highlighting that if the source string has leading whitespace, then that should be preserved in translations.

![Screenshot 2020-12-03 at 17 10 06](https://user-images.githubusercontent.com/73166588/101064524-00cc1380-358c-11eb-978f-7dfbbedf66a8.png)

This [gist](https://gist.github.com/chriswheeldon-peakon/8c679f5a0431b54dba702414b75be01a) contains sample code that replicates the bug. It creates a new source file (example.chrome.json) populated with a string with leading whitespace. It then translates that string into Danish, preserving the leading whitespace.

Many thanks, Chris

**Comment by sergo-crowdin** [comment]
@chriswheeldon-peakon, just to clarify: by "programmatically add a translation" you mean uploading a translation via API? If so, how does the request look like? Is that possible that the whitespace characters are trimmed before the request by your application or so?

**Comment by chriswheeldon-peakon** [comment]
@sergo-crowdin I don't believe so. I'm just passing a string literal to the addTranslation method of this library, like the following (lifted from the gist I attached before):

```typescript
import { StringTranslations } from "@crowdin/crowdin-api-client";

...

const stringTranslations = new StringTranslations(credentials);
await stringTranslations.addTranslation(credentials.project, {
  stringId: 1234
  languageId: "da",
  text: " Probably not valid Danish, but still prefixed with a space",
});
```

I can try and inspect the actual request or make it without going through crowdin-api-client-js to confirm where the issue lies.

**Comment by sergo-crowdin** [comment]
@chriswheeldon-peakon, that would be nice. Just to compare the behavior you may use Postman, for example

**Comment by chriswheeldon-peakon** [comment]
@sergo-crowdin it appears that the platform itself is trimming the whitespace. If I POST the following to /api/v2/projects/{projectId}/translations:

```
{
    "stringId": "5012",
    "languageId": "da",
    "text": " A translation with leading whitespace"
}
```

Then the response shows the trimmed string:

```
{
    "data": {
        "id": 5586,
        "text": "A translation with leading whitespace",
        ...
    }
}
```

**Comment by sergo-crowdin** [comment]
@chriswheeldon-peakon, thanks for trying out. We'll pass that to our developers. As soon as we get any details on the matter, we'll drop you a note here.
Would it be okay with you?

**Comment by chriswheeldon-peakon** [comment]
Absolutely, thank you @sergo-crowdin!

**Comment by andrii-bodnar** [comment]
Hi @chriswheeldon-peakon!

This issue was fixed on the API side, could you please check if everything is ok now?
