### ISSUE TITLE
 Issues Data Model difficulties

### ISSUE THREAD

**Issue by guyisra** [crowdin/crowdin-api-client-js#92]
The api is very explicit, but its data model is difficult to work with extensively.

The issues api has been deprecated and instead the StringComments is offered.
StringComments requires a stringId, which can be obtained by the Strings Api. 
However, the strings api returns all strings of a project, which can be many, and there is no way to filter them out, to get the relevant strings of which have comments that are of type issue. I must call N queries for the strings, and then check for each query if has issues, instead of directly check what issues exists (and what strings are related)

How is expected to obtain the issues of strings?

**Comment by andrii-bodnar** [comment]
Hi @guyisra!

We are going to make `stringId` optional for the [List String Comments](https://support.crowdin.com/api/v2/#operation/api.projects.strings.comments.getMany) API method. 

For now, you can use [List Reported Issues](https://support.crowdin.com/api/v2/#operation/api.projects.issues.getMany) method and then switch to **List String Comments** when `stringId` becomes optional.

**Comment by guyisra** [comment]
Thanks for the quick response
