### ISSUE TITLE
HttpClientType.FETCH doesn't work

### ISSUE THREAD

**Issue by KinectTheUnknown** [crowdin/crowdin-api-client-js#96]
Specifying the httpClientType as Fetch and making an API call seems to throw an error internally.
Code:
```js
const config = {
  projectID: 000000,
  token: "my personal access token"
}
const Crowdin = require("@crowdin/crowdin-api-client");
const translationsAPI = new (Crowdin.Translations)({
  token: config.token
}, {
  httpClientType: Crowdin.HttpClientType.FETCH
});
// Converts error to an Error object if not already
const formatError = error => error instanceof Error ? error : new Error(`${error.error.code} ${error.error.message}`)

translationsAPI.listProjectBuilds(config.projectID)
  .then(console.log, error => Promise.reject(formatError(error)))
```
  
Error:
```
ReferenceError: fetch is not defined
    at FetchClient.<anonymous> (./node_modules/@crowdin/crowdin-api-client/out/core/internal/fetch/fetchClient.js:52:13)
    at Generator.next (<anonymous>)
    at fulfilled (./node_modules/@crowdin/crowdin-api-client/out/core/internal/fetch/fetchClient.js:5:58)
```

Looking at the said file `out/core/internal/fetch/fetchClient.js`, it is indeed true that fetch isn't defined. Adding in `const fetch = require("node-fetch")` at the top of the file seems to resolve the issue. I like to use node-fetch API due to its compliance with the fetch API and I already use it, so I wouldn't need to have Axios installed. I did want to make a PR to add this, but I wanted to get your opinion on this first in case I overlooked something.

**Comment by yevheniyJ** [comment]
Hi there!
Fetch-based http client was designed to use in browser-based environment where `fetch` is already available in global scope.
We are also using this type of client in plugins where environment is neither browser nor node. But contains `fetch` in global scope.
And nevertheless `node-fetch` is not a part of Node.js runtime so it will be required then to introduce one more dependency.

Here I suggest to have a look to the possibility to define your own http client and use `node-fetch` library. You just have to follow `HttpClient` interface and implement all required methods.
Or we can consider to introduce one more http client. Something like `NODE_FETCH`.

**Comment by KinectTheUnknown** [comment]
Hello, thank you for the clarification.
I considered using the `HttpClient`  interface with `node-fetch`, but since Axios is a (required) dependency, it would still be installed whether I use it or not.
> And nevertheless node-fetch is not a part of Node.js runtime so it will be required then to introduce one more dependency.
Alternatively, you can make Axios and any other Http clients that get supported as an [optional dependency](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#optionaldependencies). In this case, the user can choose which Http client they want to use and not be forced to install every single one that's supported.

**Comment by yevheniyJ** [comment]
That's true. Right now `axios` is a required dependency and was like that from the very beginning as a main implementation and also to reduce needed steps to get use of this client (no need to install extra libraries beforehand).
But your point is completely valid but moving. We will consider to move it to `optional` dependency but this should be done carefully and probably will lead to new major version release because after it everyone will need to install `axios` if they are using default implementation and do not have `axios` installed explicitly.

**Comment by KinectTheUnknown** [comment]
I see your point. This would have to be a major change.
In such a case where the user doesn't have Axios installed, they would get an error saying that the module wasn't found and most users know that they should probably install it or check the README.md file for instructions and/or changes.
Understandably, this isn't a solution. The only solution I could think of was to use the native https module as the default Http Client. The only thing I don't like about the module is its verbosity due to the use of callbacks, but it won't be visible on the user's end anyways.

**Comment by yevheniyJ** [comment]
Still not the ideal way as native http module will be available only in Node.js environment (not in browser or non-Node.js runtime).
So definitely it will be a major release and for sure informative error handling should be in place.

**Comment by yevheniyJ** [comment]
I created a separate issue #97  for this with proper title & description and mark it as an enhancement.
