### ISSUE TITLE
crowdin is not a constructor

### ISSUE THREAD

**Issue by liantianyun** [crowdin/crowdin-api-client-js#98]
i want to use it through node.js,but i got this error:crowdin is not a constructor
the code is the example code,it's this can't work in node.js enviroment?please tell me how to fix it,thanks
for safe i hide the token
```
const crowdin = require('@crowdin/crowdin-api-client')

console.log(crowdin.toString());

// initialization of crowdin client
const { projectsGroupsApi } = new crowdin({
  token: 'mytoken',
});

// get project list
projectsGroupsApi.listProjects()
  .then(projects => console.log(projects))
  .catch(error => console.error(error));

// You can also use async/wait. Add `async` keyword to your outer function/method
async function getProjects() {
  try {
    const projects = await projectsGroupsApi.listProjects();
    console.log(projects);
  } catch (error) {
    console.error(error);
  }
}
```

**Comment by yevheniyJ** [comment]
@liantianyun  Hi there! 
Please change require statement to `const crowdin = require('@crowdin/crowdin-api-client').default`. 
After that it should work.

**Comment by yevheniyJ** [comment]
And I also updated readme as it seems like a quite common issue. Please have a look to example `Javascript CommonJS` under `Quick Start` section in readme.
And let me know if it works for you.

**Comment by liantianyun** [comment]
Ok.Thanks.Tommorrow i will test it.I'm off work today

---Original---

**Comment by liantianyun** [comment]
> And I also updated readme as it seems like a quite common issue. Please have a look to example `Javascript CommonJS` under `Quick Start` section in readme.
> And let me know if it works for you.

Hi.I tried it and found it worked, thanks ~ but it returned 401 and told me that the token was wrong, but I used the token on Crowdin

**Comment by Olena1234** [comment]
Hi! Glad to hear that it worked!
