### ISSUE TITLE
Question: Get actual text of source string

### ISSUE THREAD

**Issue by Vainock** [crowdin/crowdin-api-client-js#99]
Hello, I'm very new to JavaScript programming, so this question may seem silly, but I have no clue what I should Google.

I've got a String object from the List Strings API method and I want to get the text of this source string as a (JavaScript) string, but when I try to
`var text:string = sourceString.data.text`
VSCode outputs:
```
Type 'string | PluralText' is not assignable to type 'string'.
Type 'PluralText' is not assignable to type 'string'.
```
I know that the problem lies [here](https://github.com/crowdin/crowdin-api-client-js/blob/22ea4532467561de71406e0bf59c87536a577b60/src/sourceStrings/index.ts#L117), but I don't know what I can do about this. How can I get the actual text of this string? Btw, the Crowdin project does not contain any source strings that have the plural form.

**Comment by DimaYashchyshyn** [comment]
Hi @Vainock 
Already looking into it and investigating your comment 🙂

**Comment by yevheniyJ** [comment]
@Vainock Hi there!

Well actually `text` field can be either a plan string or `PluralText` object type.

To work properly with this kind of fields you first need to check what type exactly is currently there.

 For example in your case : 
```typescript
var text = sourceString.data.text;
if (typeof text === 'string') {
  //here text field already contains plain text
} else {
  //here we have PluralText object so get value from one of these fields: text.one || text.zero || text.two || text.few || text.many || text.other
}
```

In typescript there is syntax called type predicates https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates.
And with this you can write something like :
```typescript
function isPluralText(text: string | SourceStringsModel.PluralText): text is SourceStringsModel.PluralText {
  return text && typeof text !== 'string';
}

//then in your code

let text: string;
if (isPluralText(sourceString.data.text)) {
  text = sourceString.data.text.one
              || sourceString.data.text.zero
              || sourceString.data.text.two
              || sourceString.data.text.few
              || sourceString.data.text.many
              || sourceString.data.text.other;
} else {
  text = sourceString.data.text;
}

//now we have variable 'text' with strict string type
```

Hope this will help 🙂

**Comment by Vainock** [comment]
Thank you very much for your fast help! Now I understand how to handle this.
Thank you also for explaining it in more detail, I definitely learned something new. :)
